merge_protections:
  - name: Only merge with automerge label
    description: Allow merge only when PR has the `automerge` label
    if:
      - base = main
    success_conditions:
      - or:
          - label = automerge
