services:
  gopro-overlay-worker:
    devices:
      - ${VIDEO_WORKER_DRI_RENDER_DEVICE:-/dev/dri/renderD128}:${VIDEO_WORKER_DRI_RENDER_DEVICE:-/dev/dri/renderD128}
    environment:
      - BACKEND_GOPRO_OVERLAY_RENDER_DEVICE=${VIDEO_WORKER_DRI_RENDER_DEVICE:-/dev/dri/renderD128}
      - BACKEND_GOPRO_OVERLAY_PROFILE=${BACKEND_GOPRO_OVERLAY_PROFILE:-nvgpu}
      - BACKEND_GOPRO_OVERLAY_EXTRA_ARGS=${BACKEND_GOPRO_OVERLAY_EXTRA_ARGS:---double-buffer}
