/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThermalRouteImport } from './routes/thermal'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as ExportViewerRouteImport } from './routes/export-viewer'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewerFlightIdRouteImport } from './routes/viewer.$flightId'

const ThermalRoute = ThermalRouteImport.update({
  id: '/thermal',
  path: '/thermal',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportViewerRoute = ExportViewerRouteImport.update({
  id: '/export-viewer',
  path: '/export-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerFlightIdRoute = ViewerFlightIdRouteImport.update({
  id: '/viewer/$flightId',
  path: '/viewer/$flightId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/export-viewer': typeof ExportViewerRoute
  '/flights': typeof FlightsRoute
  '/settings': typeof SettingsRoute
  '/thermal': typeof ThermalRoute
  '/viewer/$flightId': typeof ViewerFlightIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/export-viewer': typeof ExportViewerRoute
  '/flights': typeof FlightsRoute
  '/settings': typeof SettingsRoute
  '/thermal': typeof ThermalRoute
  '/viewer/$flightId': typeof ViewerFlightIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/export-viewer': typeof ExportViewerRoute
  '/flights': typeof FlightsRoute
  '/settings': typeof SettingsRoute
  '/thermal': typeof ThermalRoute
  '/viewer/$flightId': typeof ViewerFlightIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/export-viewer'
    | '/flights'
    | '/settings'
    | '/thermal'
    | '/viewer/$flightId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/export-viewer'
    | '/flights'
    | '/settings'
    | '/thermal'
    | '/viewer/$flightId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/export-viewer'
    | '/flights'
    | '/settings'
    | '/thermal'
    | '/viewer/$flightId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ExportViewerRoute: typeof ExportViewerRoute
  FlightsRoute: typeof FlightsRoute
  SettingsRoute: typeof SettingsRoute
  ThermalRoute: typeof ThermalRoute
  ViewerFlightIdRoute: typeof ViewerFlightIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thermal': {
      id: '/thermal'
      path: '/thermal'
      fullPath: '/thermal'
      preLoaderRoute: typeof ThermalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-viewer': {
      id: '/export-viewer'
      path: '/export-viewer'
      fullPath: '/export-viewer'
      preLoaderRoute: typeof ExportViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer/$flightId': {
      id: '/viewer/$flightId'
      path: '/viewer/$flightId'
      fullPath: '/viewer/$flightId'
      preLoaderRoute: typeof ViewerFlightIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ExportViewerRoute: ExportViewerRoute,
  FlightsRoute: FlightsRoute,
  SettingsRoute: SettingsRoute,
  ThermalRoute: ThermalRoute,
  ViewerFlightIdRoute: ViewerFlightIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
