/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as ThermalRouteImport } from './routes/thermal'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as ExportViewerRouteImport } from './routes/export-viewer'
import { Route as CacheRouteImport } from './routes/cache'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewerFlightIdRouteImport } from './routes/viewer.$flightId'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/weather.lazy').then((d) => d.Route))
const ThermalRoute = ThermalRouteImport.update({
  id: '/thermal',
  path: '/thermal',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/thermal.lazy').then((d) => d.Route))
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sites.lazy').then((d) => d.Route))
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/flights.lazy').then((d) => d.Route))
const ExportViewerRoute = ExportViewerRouteImport.update({
  id: '/export-viewer',
  path: '/export-viewer',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/export-viewer.lazy').then((d) => d.Route))
const CacheRoute = CacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cache.lazy').then((d) => d.Route))
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/analytics.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerFlightIdRoute = ViewerFlightIdRouteImport.update({
  id: '/viewer/$flightId',
  path: '/viewer/$flightId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/viewer.$flightId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/cache': typeof CacheRoute
  '/export-viewer': typeof ExportViewerRoute
  '/flights': typeof FlightsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/thermal': typeof ThermalRoute
  '/weather': typeof WeatherRoute
  '/viewer/$flightId': typeof ViewerFlightIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/cache': typeof CacheRoute
  '/export-viewer': typeof ExportViewerRoute
  '/flights': typeof FlightsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/thermal': typeof ThermalRoute
  '/weather': typeof WeatherRoute
  '/viewer/$flightId': typeof ViewerFlightIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/cache': typeof CacheRoute
  '/export-viewer': typeof ExportViewerRoute
  '/flights': typeof FlightsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/thermal': typeof ThermalRoute
  '/weather': typeof WeatherRoute
  '/viewer/$flightId': typeof ViewerFlightIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/cache'
    | '/export-viewer'
    | '/flights'
    | '/login'
    | '/settings'
    | '/sites'
    | '/thermal'
    | '/weather'
    | '/viewer/$flightId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/cache'
    | '/export-viewer'
    | '/flights'
    | '/login'
    | '/settings'
    | '/sites'
    | '/thermal'
    | '/weather'
    | '/viewer/$flightId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/cache'
    | '/export-viewer'
    | '/flights'
    | '/login'
    | '/settings'
    | '/sites'
    | '/thermal'
    | '/weather'
    | '/viewer/$flightId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CacheRoute: typeof CacheRoute
  ExportViewerRoute: typeof ExportViewerRoute
  FlightsRoute: typeof FlightsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SitesRoute: typeof SitesRoute
  ThermalRoute: typeof ThermalRoute
  WeatherRoute: typeof WeatherRoute
  ViewerFlightIdRoute: typeof ViewerFlightIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thermal': {
      id: '/thermal'
      path: '/thermal'
      fullPath: '/thermal'
      preLoaderRoute: typeof ThermalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-viewer': {
      id: '/export-viewer'
      path: '/export-viewer'
      fullPath: '/export-viewer'
      preLoaderRoute: typeof ExportViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cache': {
      id: '/cache'
      path: '/cache'
      fullPath: '/cache'
      preLoaderRoute: typeof CacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer/$flightId': {
      id: '/viewer/$flightId'
      path: '/viewer/$flightId'
      fullPath: '/viewer/$flightId'
      preLoaderRoute: typeof ViewerFlightIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CacheRoute: CacheRoute,
  ExportViewerRoute: ExportViewerRoute,
  FlightsRoute: FlightsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SitesRoute: SitesRoute,
  ThermalRoute: ThermalRoute,
  WeatherRoute: WeatherRoute,
  ViewerFlightIdRoute: ViewerFlightIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
